### ISSUE TITLE
Naming of Pipes/Filters

### ISSUE THREAD

**Issue by Eisfunke** [jgm/doctemplates#10]
Just a heads-up: pipes are called, well, "pipes" in the [readme](https://github.com/jgm/doctemplates#pipes), the Pandoc manual and the [code itself](https://github.com/jgm/doctemplates/blob/43d970a05e061147d4f1d89e5d65c1e2d25d7bd6/src/Text/DocTemplates/Internal.hs#L87), but in the [haddock doc](https://github.com/jgm/doctemplates/blob/43d970a05e061147d4f1d89e5d65c1e2d25d7bd6/src/Text/DocTemplates.hs#L312) they're called "filters".

Is that intentional? Using the same name consistently would probably be a good idea to prevent confusion.

**Comment by jgm** [comment]
We changed to pipes in d2e4d0d946f7cc188307c4102a314cdd737469ca
But we didn't update the haddocks (I need to do `make haddock` which creates the haddocks from the README.)

**Comment by jgm** [comment]
thanks for noticing this!
